### ISSUE TITLE
RxReact.createClass

### ISSUE THREAD

**Issue by fdecampredon** [fdecampredon/rx-react#12]
# New Factory for RxReact Components

In 0.3 I'll introduce a new way of creating RxReact components trough some sort of factory.
The goal is to provide a more 'Rx' compatible way of working with react, less based on OOP concept, and more based on pure function and Observable Composition.
A very early implementation has landed in master just now, and you can see an example [here](https://github.com/fdecampredon/rx-react/blob/master/examples/todolist/index.js).

However I'm still hesitant between 2 different API , since a piece of code is a lot more clear that my poor english explanations, here are 2 very basic todolist implemented with both API.

##  Higher Order Function
```Javascript
'use strict';

const React = require('react');
const Rx = require('rx');
const RxReact = require('rx-react');
const ReactDOM = require('react-dom');

class TodoList {
  render() {
    const { items } = this.props;
    return (
      <ul>{items.map((itemText, index) => 
        <li key={index + itemText}>{itemText}</li>
      )}</ul>
    );
  }
}

const TodoApp = RxReact.createClass(function TodoApp() {
  
  const onChange = RxReact.FuncSubject.create();
  
  const handleSubmit = RxReact.FuncSubject.create(function (e) {
    e.preventDefault();
  });
  
  const inputValueStream = (
    onChange
    .map(e => e.target.value)
    .startWith('')
  );
  
  const itemsStream = (
      handleSubmit
      .withLatestFrom(inputValueStream, (_, text) => text )
      .scan((items, text) => items.concat(text), [])
      .startWith([])
  );
  
  const textStream = inputValueStream.merge(handleSubmit.map(''));
  
  const stateStream = Rx.Observable.combineLatest(
    textStream,
    itemsStream,
    (text, items) => ({ text, items })
  );

  function render({state: {items, text}}) {
    return (
      <div>
        <h3>TODO</h3>
        <TodoList items={items} />
        <form onSubmit={handleSubmit}>
          <input onChange={onChange} value={text} />
          <button>{'Add #' + (items.length + 1)}</button>
        </form>
      </div>
    );
  }
  return {render, stateStream};
});

ReactDOM.render(<TodoApp />, document.getElementById('container'));
```

##  Declared events

```Javascript
'use strict';

const React = require('react');
const Rx = require('rx');
const RxReact = require('rx-react');
const ReactDOM = require('react-dom');

class TodoList {
  render() {
    const { items } = this.props;
    return (
      <ul>{items.map((itemText, index) => 
        <li key={index + itemText}>{itemText}</li>
      )}</ul>
    );
  }
}

const TodoApp = RxReact.createClass({
  displayName: 'TodoApp',
   
  events: () => ({
    onChange: RxReact.FuncSubject.create(),
    handleSubmit: RxReact.FuncSubject.create(e => e.preventDefault())
  }),
  
  getStateStream({ events: {onChange, handleSubmit } }) {
    const inputValueStream = (
      onChange
      .map(e => e.target.value)
      .startWith('')
    );

    const itemsStream = (
        handleSubmit
        .withLatestFrom(inputValueStream, (_, text) => text )
        .scan((items, text) => items.concat(text), [])
        .startWith([])
    );

    const textStream = inputValueStream.merge(handleSubmit.map(''));

    return Rx.Observable.combineLatest(
      textStream,
      itemsStream,
      (text, items) => ({ text, items })
    );
  },
 
 
  render({state: {items, text}, events: {onChange, handleSubmit}}) {
    return (
      <div>
        <h3>TODO</h3>
        <TodoList items={items} />
        <form onSubmit={handleSubmit}>
          <input onChange={onChange} value={text} />
          <button>{'Add #' + (items.length + 1)}</button>
        </form>
      </div>
    );
  }
});

ReactDOM.render(<TodoApp />, document.getElementById('container'));
```

While the first API seems a lot more simple and create less constraints for the developper; the second one could greatly improve testability: One could simply test the different parts of the spec object instead of the whole component.
However it creates some problems when you want to access state of the components inside of an event handler.
It would certainly require some extra works/magic inside RxReact to handle this problem  (like passing props/state as argument of the events handler like for the [Returning state pattern](https://github.com/reactjs/react-future/blob/master/07%20-%20Returning%20State/01%20-%20Stateful%20Functions.js) described in react-future), and I'm not really sure it worths the complexity.

**Comment by haf** [comment]
I have a similar example to you, but want to pass the event on to the parent component. With the first example, there's no 'this' that I can easily hold on to. How would you solve that with the first alternative?

**Comment by fdecampredon** [comment]
You have 2 way of doing so : 
```javascript
class Container  {
  render() {
    return <Child onClick={() => alert('hello')} />
  }
}

var Child = RxReact.createClass(function Child() {
   var stateStream = ...;
   function render(props) {
     return <div onClick={props.onClick} >....</div>;
   }
   return {stateStream, render}
});
```
Complex : 
```javascript
class Container  {
  render() {
    return <Child onClick={() => alert('hello')} />
  }
}

var Child = RxReact.createClass(function Child(propsStream) {
   var onClick = FuncSubject.create();
   onClick.combineLatest(propsStream, function (event, props) {
     return  props
   })
   .subscribe(props => props.onClick(event));
  
   var stateStream = ...;
   function render(props) {
     return <div onClick={props.onClick} >....</div>;
   }
   return {stateStream, render}
});
```

**Comment by haf** [comment]
I'm not sure I follow completely. What I was trying to get at was how values are passed as arguments to render versus to the constructor function in `RxReact.createClass(function CtorFn( HERE ) {`.

Are you considering passing propsStream to the constructor function? And the two samples above doesn't showcase receiving props as an argument in `render()` either; is this under consideration?

**Comment by haf** [comment]
Also, are you sure you aren't thinking of `withLatestFrom` rather than `combineLatest`? Combine latest will fire a value for each click and for each updated prop value, but you really only want to fire with the latest from the prop values every click?

**Comment by fdecampredon** [comment]
yes @haf the propsStream is passed to the constructor function. And yes withLatestFrom would be more suited here ^^.

**Comment by fdecampredon** [comment]
btw there is already and implementation of createClass in master, I'm currently experimenting with it in a project

**Comment by haf** [comment]
I'm writing an [open source chat](https://github.com/haf/suave-presentation.2015-09-03) with this project, saw the example on master and was a bit sad when it wasn't available right now ;)

Thanks for writing the library.

**Comment by fdecampredon** [comment]
be carefull however I'm really not sure it will ends up being the final API, I'm still not convinced.

**Comment by fdecampredon** [comment]
After trying both those API in pet project I think that they bring no value over the classic class based system.
Sure getting ride of `this` is cool but it does not worth loosing all the compatibility with other react project.
