### ISSUE TITLE
Lifecycle for RxReact.Component

### ISSUE THREAD

**Issue by geowa4** [fdecampredon/rx-react#15]
I'm trying to extend Component as well as use FuncSubject. The issue is that Component overrides `componentWillMount` where I'd like to create the FuncSubject. Any tips on what to do? Building on the comment tutorial from React's documentation, I've illustrated my present workaround below. I'd be happy to submit any PRs, but I figured I'd ask first.

```
export class CommentComponent extends RxReact.Component {
  getStateStream () {
    this.makeComment = RxReact.FuncSubject.create();
    this.makeComment
      .forEach(makeComment);

    return commentListStream.map(list => {
      return { data: list }
    });
  }

  render () {
    return (
      <div className="commentBox">
        <h1>Comments</h1>
        <CommentList data={this.state.data} />
        <CommentForm onCommentSubmit={this.makeComment} />
      </div>
    );
  }
}
```

**Comment by fdecampredon** [comment]
I don't really understand your problem here, Creating FuncSubject in getStateStream is a good pattern. 
Also if you wish to have a component will mount just use `super`: 
```Javascript
class MyComp extends RxReact.Component {
  componentWillMount() {
    super.componentWillMount();
    ....
  }
  ....
}
```
Is there something else ?

**Comment by geowa4** [comment]
Using `super` would work. Thanks.

My problem with putting that in `getStateStream` is the incongruence between the actions and the name of the method. I'd be making a Subject where I should only be retrieving an Observable to be used as my component's state; "query xor update" would be violated.

**Comment by fdecampredon** [comment]
To be honest I generally use ES7 class property declaration : 

```
class MyComponent extends RxReact.Component {
  buttonClick = FuncSubject.create(); 
  getStateStream() {
    return this.buttonClick.map(...)
  }
}
```
you can also use the constructor
