### ISSUE TITLE
How can I use it with ES6 classes?

### ISSUE THREAD

**Issue by tusharmath** [fdecampredon/rx-react#20]
There is [no support](https://facebook.github.io/react/docs/reusable-components.html#no-mixins) for mixins in es6 classes.

**Comment by fdecampredon** [comment]
https://github.com/fdecampredon/rx-react#component

**Comment by tusharmath** [comment]
Thanks!

On Sun, Dec 20, 2015, 2:11 PM François de Campredon <
notifications@github.com> wrote:

> https://github.com/fdecampredon/rx-react#component
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fdecampredon/rx-react/issues/20#issuecomment-166085546>
> .
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com
