### ISSUE TITLE
What advantages does Rx bring to the normal Callback React flow?

### ISSUE THREAD

**Issue by abergs** [fdecampredon/rx-react#5]
Hey mate!

I'm genuinely interested in Rx and i'm just starting out learning more about Reactive Extenstions, FRP and other techniques (csp, channels).

And since we've spoken before about react related matters i'd just like to ask you what Rx brings to the table in an application based on React + flux.

Cheers mate,
Anders

**Comment by tomchentw** [comment]
IMO, choose either one:
* React + Redux
* Rx + Cycle-React

**Comment by tusharmath** [comment]
For instance — It gives a consistent api to interact with, whether you are using react or not. Whether you are working with async jobs or not etc.

**Comment by fdecampredon** [comment]
Sorry for the delay answering :D I'll give a talk at http://reactive2015.com/ on reactive programming with react.
Basicly I think that the main advantage is to be able to get a declarative approach from user events to component state.
