### ISSUE TITLE
Webpack: Cannot resolve module 'rx-react'

### ISSUE THREAD

**Issue by geraldyeo** [fdecampredon/rx-react#7]
Hi,

I'm getting this error in my Webpack build:
`Module not found: Error: Cannot resolve module 'rx-react' in [...]`

Do I need to specify anything in my webpack config for `rx-react` to be included?

**Comment by tomchentw** [comment]
I believe this was related to #6 . Using the git form in `package.json` solves this:
```js
    "rx-react": "git+git@github.com:fdecampredon/rx-react.git#master"
```
It would be great if @fdecampredon could publish a patch version (v0.2.1) to npm.

**Comment by overture8** [comment]
Yeah, I'm getting this issue too.

**Comment by goldensunliu** [comment]
+1

**Comment by mmoutenot** [comment]
here too!

**Comment by goldensunliu** [comment]
@tomchentw 

```
 "rx-react": "git+git@github.com:fdecampredon/rx-react.git#master"
```
doesn't seem to work

**Comment by chcokr** [comment]
```
"rx-react": "fdecampredon/rx-react"
```
does the trick

@fdecampredon  Please publish to npm

**Comment by fdecampredon** [comment]
I'll update some minor thing today and publish 0.2.1
Here is the roadmap for 0.3 that should be ready soon : 
* Better func subject (possibility of using Behavior or Custom subject, map function etc ...)
* Deprecation of Lifecycle in Class component
* new method for creating rx react component  based on : https://gist.github.com/fdecampredon/8b5f537bacb6e2bda99b

**Comment by fdecampredon** [comment]
done
